name: Push component to https://components.espressif.com
on:
  push:
    tags:
      - v*

jobs:
  upload_components:
    if: github.repository == 'udoudou/esp_cherryusb'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Upload component to the component registry
        uses: espressif/upload-components-ci-action@v1
        with:
          name: "esp_cherryusb"
          version: ${{ github.ref_name }}
          namespace: "udoudou"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
